#include <libcore/devices/memory_access_protocol.test.cpp>  // NOLINT
#include <libcore/devices/parallel_bus.test.cpp>            // NOLINT
#include <libcore/devices/servo.test.cpp>                   // NOLINT
#include <libcore/peripherals/adc.test.cpp>                 // NOLINT
#include <libcore/peripherals/can.test.cpp>                 // NOLINT
#include <libcore/peripherals/gpio.test.cpp>                // NOLINT
#include <libcore/peripherals/hardware_counter.test.cpp>    // NOLINT
#include <libcore/peripherals/i2c.test.cpp>                 // NOLINT
#include <libcore/peripherals/interrupt.test.cpp>           // NOLINT
#include <libcore/peripherals/pwm.test.cpp>                 // NOLINT
#include <libcore/peripherals/uart.test.cpp>                // NOLINT
#include <libcore/systems/graphical_terminal.test.cpp>      // NOLINT
#include <libcore/systems/graphics.test.cpp>                // NOLINT
#include <libcore/utility/build_info.test.cpp>              // NOLINT
#include <libcore/utility/constexpr.test.cpp>               // NOLINT
#include <libcore/utility/enum.test.cpp>                    // NOLINT
#include <libcore/utility/error_handling.test.cpp>          // NOLINT
#include <libcore/utility/infrared_algorithms.test.cpp>     // NOLINT
#include <libcore/utility/math/average.test.cpp>            // NOLINT
#include <libcore/utility/math/bit.test.cpp>                // NOLINT
#include <libcore/utility/math/byte.test.cpp>               // NOLINT
#include <libcore/utility/math/crc.test.cpp>                // NOLINT
#include <libcore/utility/math/limits.test.cpp>             // NOLINT
#include <libcore/utility/math/map.test.cpp>                // NOLINT
#include <libcore/utility/memory_resource.test.cpp>         // NOLINT
#include <libcore/utility/time/stopwatch.test.cpp>          // NOLINT
#include <libcore/utility/time/time.test.cpp>               // NOLINT
#include <libcore/utility/time/timeout_timer.test.cpp>      // NOLINT